=== kant/graced/GrACED/files/results/ClassifiedTablesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ClassifiedTablesSchema" xmlns:tns="http://www.example.org/ClassifiedTablesSchema" elementFormDefault="qualified">


    <element name="root" type="tns:RootType"></element>
    

    <complexType name="RootType">
    	<sequence>
    		<element name="tables" type="tns:TableType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="TableType">
    	<sequence>
    		<element ref="tns:class" maxOccurs="unbounded"
    			minOccurs="1">
    		</element>
    		<element ref="tns:column" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute ref="tns:tableName"></attribute>
    </complexType>

    <complexType name="InfoType">
    	<attribute ref="tns:classPercent"></attribute>
    </complexType>



    <attribute name="tableName" type="string"></attribute>

    <attribute name="className" type="string"></attribute>

    <attribute name="classPercent" type="double"></attribute>

    <element name="class" type="tns:ClassType"></element>

    <complexType name="ClassType">
    	<sequence>
    		<element ref="tns:tableClassification" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element ref="tns:columnClassification" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute ref="tns:className"></attribute>
    	<attribute ref="tns:classPercent"></attribute>
    </complexType>

    <element name="tableClassification" type="tns:InfoType"></element>
    
    <element name="columnClassification" type="tns:InfoType"></element>

    <attribute name="columnName" type="string"></attribute>

    <element name="column" type="tns:ColumnType"></element>
    
    <complexType name="ColumnType">
    	<attribute ref="tns:columnName"></attribute>
    </complexType>
</schema>

=== kant/graced/GrACED/files/results/ClassifiedTables_openerpdb.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:root xmlns:tns="http://www.example.org/BagOfWordsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ClassifiedTablesSchema ../results/ClassifiedTablesSchema.xsd ">
<tns:tables tns:tableName="employee_category_rel">
<tns:class tns:className="Bill Of Resources" tns:classPercent="13.56">
<tns:tableClassification tns:classPercent="22.0"/>
<tns:columnClassification tns:classPercent="5.12"/>
</tns:class>
<tns:column tns:columnName="category_id"/>
<tns:column tns:columnName="emp_id"/>
</tns:tables>
<tns:tables tns:tableName="hr_department">
<tns:class tns:className="Bill Of Resources" tns:classPercent="10.92">
<tns:tableClassification tns:classPercent="16.0"/>
<tns:columnClassification tns:classPercent="5.840000000000001"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="name"/>
<tns:column tns:columnName="company_id"/>
<tns:column tns:columnName="note"/>
<tns:column tns:columnName="parent_id"/>
<tns:column tns:columnName="manager_id"/>
</tns:tables>
<tns:tables tns:tableName="hr_employee">
<tns:class tns:className="Bill Of Resources" tns:classPercent="30.265">
<tns:tableClassification tns:classPercent="32.0"/>
<tns:columnClassification tns:classPercent="28.529999999999998"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="address_id"/>
<tns:column tns:columnName="coach_id"/>
<tns:column tns:columnName="resource_id"/>
<tns:column tns:columnName="color"/>
<tns:column tns:columnName="image"/>
<tns:column tns:columnName="marital"/>
<tns:column tns:columnName="identification_id"/>
<tns:column tns:columnName="bank_account_id"/>
<tns:column tns:columnName="job_id"/>
<tns:column tns:columnName="work_phone"/>
<tns:column tns:columnName="country_id"/>
<tns:column tns:columnName="parent_id"/>
<tns:column tns:columnName="notes"/>
<tns:column tns:columnName="department_id"/>
<tns:column tns:columnName="otherid"/>
<tns:column tns:columnName="mobile_phone"/>
<tns:column tns:columnName="birthday"/>
<tns:column tns:columnName="sinid"/>
<tns:column tns:columnName="work_email"/>
<tns:column tns:columnName="work_location"/>
<tns:column tns:columnName="image_medium"/>
<tns:column tns:columnName="name_related"/>
<tns:column tns:columnName="ssnid"/>
<tns:column tns:columnName="image_small"/>
<tns:column tns:columnName="address_home_id"/>
<tns:column tns:columnName="gender"/>
<tns:column tns:columnName="passport_id"/>
</tns:tables>
<tns:tables tns:tableName="hr_job">
<tns:class tns:className="Bill Of Resources" tns:classPercent="18.779999999999994">
<tns:tableClassification tns:classPercent="26.0"/>
<tns:columnClassification tns:classPercent="11.559999999999992"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="requirements"/>
<tns:column tns:columnName="name"/>
<tns:column tns:columnName="description"/>
<tns:column tns:columnName="company_id"/>
<tns:column tns:columnName="state"/>
<tns:column tns:columnName="no_of_recruitment"/>
<tns:column tns:columnName="expected_employees"/>
<tns:column tns:columnName="no_of_employee"/>
<tns:column tns:columnName="department_id"/>
</tns:tables>
<tns:tables tns:tableName="mrp_bom">
<tns:class tns:className="Bill Of Materials" tns:classPercent="56.34">
<tns:tableClassification tns:classPercent="50.0"/>
<tns:columnClassification tns:classPercent="62.68000000000001"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="date_stop"/>
<tns:column tns:columnName="code"/>
<tns:column tns:columnName="product_uom"/>
<tns:column tns:columnName="product_uos_qty"/>
<tns:column tns:columnName="date_start"/>
<tns:column tns:columnName="product_qty"/>
<tns:column tns:columnName="product_uos"/>
<tns:column tns:columnName="product_efficiency"/>
<tns:column tns:columnName="active"/>
<tns:column tns:columnName="product_rounding"/>
<tns:column tns:columnName="name"/>
<tns:column tns:columnName="sequence"/>
<tns:column tns:columnName="company_id"/>
<tns:column tns:columnName="routing_id"/>
<tns:column tns:columnName="product_id"/>
<tns:column tns:columnName="bom_id"/>
<tns:column tns:columnName="position"/>
<tns:column tns:columnName="type"/>
</tns:tables>
<tns:tables tns:tableName="mrp_bom_property_rel">
<tns:class tns:className="Bill Of Materials" tns:classPercent="31.57">
<tns:tableClassification tns:classPercent="53.0"/>
<tns:columnClassification tns:classPercent="10.14"/>
</tns:class>
<tns:column tns:columnName="bom_id"/>
<tns:column tns:columnName="property_id"/>
</tns:tables>
<tns:tables tns:tableName="mrp_config_settings">
<tns:class tns:className="Bill Of Materials" tns:classPercent="19.71">
<tns:tableClassification tns:classPercent="25.0"/>
<tns:columnClassification tns:classPercent="14.420000000000002"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="module_mrp_byproduct"/>
<tns:column tns:columnName="module_mrp_jit"/>
<tns:column tns:columnName="group_mrp_properties"/>
<tns:column tns:columnName="module_product_manufacturer"/>
<tns:column tns:columnName="module_mrp_repair"/>
<tns:column tns:columnName="module_mrp_operations"/>
<tns:column tns:columnName="group_mrp_routings"/>
<tns:column tns:columnName="module_stock_no_autopicking"/>
</tns:tables>
<tns:tables tns:tableName="mrp_product_price">
<tns:class tns:className="Bill Of Materials" tns:classPercent="24.14">
<tns:tableClassification tns:classPercent="41.0"/>
<tns:columnClassification tns:classPercent="7.28"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="number"/>
</tns:tables>
<tns:tables tns:tableName="mrp_product_produce">
<tns:class tns:className="Bill Of Materials" tns:classPercent="27.64">
<tns:tableClassification tns:classPercent="40.0"/>
<tns:columnClassification tns:classPercent="15.280000000000001"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="mode"/>
<tns:column tns:columnName="product_qty"/>
</tns:tables>
<tns:tables tns:tableName="mrp_production">
<tns:class tns:className="Bill Of Materials" tns:classPercent="39.480000000000004">
<tns:tableClassification tns:classPercent="26.0"/>
<tns:columnClassification tns:classPercent="52.96000000000001"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="origin"/>
<tns:column tns:columnName="product_uom"/>
<tns:column tns:columnName="product_uos_qty"/>
<tns:column tns:columnName="product_qty"/>
<tns:column tns:columnName="product_uos"/>
<tns:column tns:columnName="user_id"/>
<tns:column tns:columnName="location_src_id"/>
<tns:column tns:columnName="cycle_total"/>
<tns:column tns:columnName="date_start"/>
<tns:column tns:columnName="company_id"/>
<tns:column tns:columnName="priority"/>
<tns:column tns:columnName="state"/>
<tns:column tns:columnName="bom_id"/>
<tns:column tns:columnName="date_finished"/>
<tns:column tns:columnName="name"/>
<tns:column tns:columnName="product_id"/>
<tns:column tns:columnName="date_planned"/>
<tns:column tns:columnName="move_prod_id"/>
<tns:column tns:columnName="routing_id"/>
<tns:column tns:columnName="hour_total"/>
<tns:column tns:columnName="location_dest_id"/>
<tns:column tns:columnName="picking_id"/>
</tns:tables>
<tns:tables tns:tableName="mrp_production_product_line">
<tns:class tns:className="Bill Of Materials" tns:classPercent="39.71">
<tns:tableClassification tns:classPercent="42.0"/>
<tns:columnClassification tns:classPercent="37.42"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="product_uos_qty"/>
<tns:column tns:columnName="name"/>
<tns:column tns:columnName="product_uom"/>
<tns:column tns:columnName="product_qty"/>
<tns:column tns:columnName="product_uos"/>
<tns:column tns:columnName="production_id"/>
<tns:column tns:columnName="product_id"/>
</tns:tables>
<tns:tables tns:tableName="mrp_production_workcenter_line">
<tns:class tns:className="Bill Of Resources" tns:classPercent="13.92">
<tns:tableClassification tns:classPercent="17.0"/>
<tns:columnClassification tns:classPercent="10.84"/>
</tns:class>
<tns:class tns:className="Bill Of Materials" tns:classPercent="17.78">
<tns:tableClassification tns:classPercent="27.0"/>
<tns:columnClassification tns:classPercent="8.56"/>
</tns:class>
<tns:column tns:columnName="id"/>
<tns:column tns:columnName="create_uid"/>
<tns:column tns:columnName="create_date"/>
<tns:column tns:columnName="write_date"/>
<tns:column tns:columnName="write_uid"/>
<tns:column tns:columnName="name"/>
