=== kant/graced/GrACED/files/results/UnclassifiedTablesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/UnclassifiedTablesSchema" xmlns:tns="http://www.example.org/UnclassifiedTablesSchema" elementFormDefault="qualified">

    <element name="root" type="tns:RootType"></element>
    
    <complexType name="RootType">
    	<sequence>
    		<element ref="tns:table" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <element name="table" type="tns:TableType"></element>
    
    <attribute name="tableName" type="string"></attribute>

    <complexType name="TableType">
    	<attribute ref="tns:tableName"></attribute>
    </complexType>
</schema>

=== kant/graced/GrACED/files/results/UnclassifiedTables_openerpdb.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:root xmlns:tns="http://www.example.org/BagOfWordsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/UnclassifiedTablesSchema ../results/UnclassifiedTablesSchema.xsd ">
<tns:table tns:tableName="account_account"/>
<tns:table tns:tableName="account_account_consol_rel"/>
<tns:table tns:tableName="account_account_financial_report"/>
<tns:table tns:tableName="account_account_financial_report_type"/>
<tns:table tns:tableName="account_account_tax_default_rel"/>
<tns:table tns:tableName="account_account_template"/>
<tns:table tns:tableName="account_account_template_tax_rel"/>
<tns:table tns:tableName="account_account_type"/>
<tns:table tns:tableName="account_account_type_rel"/>
<tns:table tns:tableName="account_addtmpl_wizard"/>
<tns:table tns:tableName="account_aged_trial_balance"/>
<tns:table tns:tableName="account_aged_trial_balance_journal_rel"/>
<tns:table tns:tableName="account_analytic_account"/>
<tns:table tns:tableName="account_analytic_balance"/>
<tns:table tns:tableName="account_analytic_chart"/>
<tns:table tns:tableName="account_analytic_cost_ledger"/>
<tns:table tns:tableName="account_analytic_cost_ledger_journal_report"/>
<tns:table tns:tableName="account_analytic_inverted_balance"/>
<tns:table tns:tableName="account_analytic_journal"/>
<tns:table tns:tableName="account_analytic_journal_name"/>
<tns:table tns:tableName="account_analytic_journal_report"/>
<tns:table tns:tableName="account_analytic_line"/>
<tns:table tns:tableName="account_automatic_reconcile"/>
<tns:table tns:tableName="account_balance_report"/>
<tns:table tns:tableName="account_balance_report_journal_rel"/>
<tns:table tns:tableName="account_bank_accounts_wizard"/>
<tns:table tns:tableName="account_bank_statement"/>
<tns:table tns:tableName="account_bank_statement_line"/>
<tns:table tns:tableName="account_bank_statement_line_move_rel"/>
<tns:table tns:tableName="account_cashbox_line"/>
<tns:table tns:tableName="account_central_journal"/>
<tns:table tns:tableName="account_central_journal_journal_rel"/>
<tns:table tns:tableName="account_change_currency"/>
<tns:table tns:tableName="account_chart"/>
<tns:table tns:tableName="account_chart_template"/>
<tns:table tns:tableName="account_common_account_report"/>
<tns:table tns:tableName="account_common_account_report_account_journal_rel"/>
<tns:table tns:tableName="account_common_journal_report"/>
<tns:table tns:tableName="account_common_journal_report_account_journal_rel"/>
<tns:table tns:tableName="account_common_partner_report"/>
<tns:table tns:tableName="account_common_partner_report_account_journal_rel"/>
<tns:table tns:tableName="account_common_report"/>
<tns:table tns:tableName="account_common_report_account_journal_rel"/>
<tns:table tns:tableName="account_config_settings"/>
<tns:table tns:tableName="account_entries_report"/>
<tns:table tns:tableName="account_financial_report"/>
<tns:table tns:tableName="account_fiscal_position"/>
<tns:table tns:tableName="account_fiscal_position_account"/>
<tns:table tns:tableName="account_fiscal_position_account_template"/>
<tns:table tns:tableName="account_fiscal_position_tax"/>
<tns:table tns:tableName="account_fiscal_position_tax_template"/>
<tns:table tns:tableName="account_fiscal_position_template"/>
<tns:table tns:tableName="account_fiscalyear"/>
<tns:table tns:tableName="account_fiscalyear_close"/>
<tns:table tns:tableName="account_fiscalyear_close_state"/>
<tns:table tns:tableName="account_general_journal"/>
<tns:table tns:tableName="account_general_journal_journal_rel"/>
<tns:table tns:tableName="account_installer"/>
<tns:table tns:tableName="account_invoice"/>
<tns:table tns:tableName="account_invoice_cancel"/>
<tns:table tns:tableName="account_invoice_confirm"/>
<tns:table tns:tableName="account_invoice_line"/>
<tns:table tns:tableName="account_invoice_line_tax"/>
<tns:table tns:tableName="account_invoice_refund"/>
<tns:table tns:tableName="account_invoice_report"/>
<tns:table tns:tableName="account_invoice_tax"/>
<tns:table tns:tableName="account_journal"/>
<tns:table tns:tableName="account_journal_account_vat_declaration_rel"/>
<tns:table tns:tableName="account_journal_accounting_report_rel"/>
<tns:table tns:tableName="account_journal_cashbox_line"/>
<tns:table tns:tableName="account_journal_group_rel"/>
<tns:table tns:tableName="account_journal_period"/>
<tns:table tns:tableName="account_journal_select"/>
<tns:table tns:tableName="account_journal_type_rel"/>
<tns:table tns:tableName="account_model"/>
<tns:table tns:tableName="account_model_line"/>
<tns:table tns:tableName="account_move"/>
<tns:table tns:tableName="account_move_bank_reconcile"/>
<tns:table tns:tableName="account_move_line"/>
<tns:table tns:tableName="account_move_line_reconcile"/>
<tns:table tns:tableName="account_move_line_reconcile_select"/>
<tns:table tns:tableName="account_move_line_reconcile_writeoff"/>
<tns:table tns:tableName="account_move_line_relation"/>
<tns:table tns:tableName="account_move_line_unreconcile_select"/>
<tns:table tns:tableName="account_move_reconcile"/>
<tns:table tns:tableName="account_open_closed_fiscalyear"/>
<tns:table tns:tableName="account_partner_balance"/>
<tns:table tns:tableName="account_partner_balance_journal_rel"/>
<tns:table tns:tableName="account_partner_ledger"/>
<tns:table tns:tableName="account_partner_ledger_journal_rel"/>
<tns:table tns:tableName="account_partner_reconcile_process"/>
<tns:table tns:tableName="account_payment_term"/>
<tns:table tns:tableName="account_payment_term_line"/>
<tns:table tns:tableName="account_period"/>
<tns:table tns:tableName="account_period_close"/>
<tns:table tns:tableName="account_print_journal"/>
<tns:table tns:tableName="account_print_journal_journal_rel"/>
<tns:table tns:tableName="account_report_general_ledger"/>
<tns:table tns:tableName="account_report_general_ledger_journal_rel"/>
<tns:table tns:tableName="account_sequence_fiscalyear"/>
<tns:table tns:tableName="account_state_open"/>
<tns:table tns:tableName="account_statement_from_invoice_lines"/>
<tns:table tns:tableName="account_subscription"/>
<tns:table tns:tableName="account_subscription_generate"/>
<tns:table tns:tableName="account_subscription_line"/>
<tns:table tns:tableName="account_tax"/>
<tns:table tns:tableName="account_tax_chart"/>
<tns:table tns:tableName="account_tax_code"/>
<tns:table tns:tableName="account_tax_code_template"/>
<tns:table tns:tableName="account_tax_template"/>
<tns:table tns:tableName="account_template_financial_report"/>
<tns:table tns:tableName="account_treasury_report"/>
<tns:table tns:tableName="account_unreconcile"/>
<tns:table tns:tableName="account_unreconcile_reconcile"/>
<tns:table tns:tableName="account_use_model"/>
<tns:table tns:tableName="account_use_model_relation"/>
<tns:table tns:tableName="account_vat_declaration"/>
<tns:table tns:tableName="account_voucher"/>
<tns:table tns:tableName="account_voucher_line"/>
<tns:table tns:tableName="accounting_report"/>
<tns:table tns:tableName="action_traceability"/>
<tns:table tns:tableName="analytic_entries_report"/>
<tns:table tns:tableName="base_config_settings"/>
<tns:table tns:tableName="base_language_export"/>
<tns:table tns:tableName="base_language_import"/>
<tns:table tns:tableName="base_language_install"/>
<tns:table tns:tableName="base_module_configuration"/>
<tns:table tns:tableName="base_module_import"/>
<tns:table tns:tableName="base_module_update"/>
<tns:table tns:tableName="base_module_upgrade"/>
<tns:table tns:tableName="base_setup_terminology"/>
<tns:table tns:tableName="base_update_translations"/>
<tns:table tns:tableName="board_create"/>
<tns:table tns:tableName="cash_box_in"/>
<tns:table tns:tableName="cash_box_out"/>
<tns:table tns:tableName="change_password_user"/>
<tns:table tns:tableName="change_password_wizard"/>
<tns:table tns:tableName="change_production_qty"/>
<tns:table tns:tableName="decimal_precision"/>
<tns:table tns:tableName="email_template"/>
<tns:table tns:tableName="email_template_attachment_rel"/>
<tns:table tns:tableName="email_template_preview"/>
<tns:table tns:tableName="fetchmail_config_settings"/>
<tns:table tns:tableName="fetchmail_server"/>
<tns:table tns:tableName="hr_config_settings"/>
<tns:table tns:tableName="hr_employee_category"/>
<tns:table tns:tableName="ir_act_client"/>
<tns:table tns:tableName="ir_act_report_custom"/>
<tns:table tns:tableName="ir_act_report_xml"/>
<tns:table tns:tableName="ir_act_server"/>
<tns:table tns:tableName="ir_act_url"/>
<tns:table tns:tableName="ir_act_window"/>
<tns:table tns:tableName="ir_act_window_group_rel"/>
<tns:table tns:tableName="ir_act_window_view"/>
<tns:table tns:tableName="ir_act_wizard"/>
<tns:table tns:tableName="ir_actions"/>
<tns:table tns:tableName="ir_actions_configuration_wizard"/>
<tns:table tns:tableName="ir_actions_todo"/>
<tns:table tns:tableName="ir_attachment"/>
<tns:table tns:tableName="ir_config_parameter"/>
<tns:table tns:tableName="ir_cron"/>
<tns:table tns:tableName="ir_default"/>
<tns:table tns:tableName="ir_exports"/>
<tns:table tns:tableName="ir_exports_line"/>
<tns:table tns:tableName="ir_fields_converter"/>
<tns:table tns:tableName="ir_filters"/>
<tns:table tns:tableName="ir_mail_server"/>
<tns:table tns:tableName="ir_model"/>
<tns:table tns:tableName="ir_model_access"/>
<tns:table tns:tableName="ir_model_constraint"/>
<tns:table tns:tableName="ir_model_data"/>
<tns:table tns:tableName="ir_model_fields"/>
<tns:table tns:tableName="ir_model_fields_group_rel"/>
<tns:table tns:tableName="ir_model_relation"/>
<tns:table tns:tableName="ir_module_category"/>
<tns:table tns:tableName="ir_module_module"/>
<tns:table tns:tableName="ir_module_module_dependency"/>
<tns:table tns:tableName="ir_property"/>
<tns:table tns:tableName="ir_rule"/>
<tns:table tns:tableName="ir_sequence"/>
<tns:table tns:tableName="ir_sequence_type"/>
<tns:table tns:tableName="ir_server_object_lines"/>
<tns:table tns:tableName="ir_translation"/>
